# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Shawn's Ramblings
email: shawnw.mobile@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog. About code.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://shawnw.github.io" # the base hostname & protocol for your site
github_username: shawnw
theme: jekyll-theme-hacker

# Build settings
markdown: kramdown
